VPATH = src bins libs objs 

make_dirs:
	mkdir -p ${VPATH}

make_src_dirs: make_dirs 
	mkdir -p src/mod1
	mkdir -p src/mod2 
	mkdir -p src/mod3 
	mkdir -p src/mod4 
	mkdir -p src/mod5 
clean:
	rm -rf ${VPATH}


